"""empty message

Revision ID: 055391d9f45f
Revises: 08b5cc247560
Create Date: 2021-11-06 19:17:16.290944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055391d9f45f'
down_revision = '08b5cc247560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient', sa.Text(), nullable=False))
        batch_op.drop_column('Ingredient')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Ingredient', sa.TEXT(), nullable=False))
        batch_op.drop_column('ingredient')

    # ### end Alembic commands ###
