"""empty message

Revision ID: 08b5cc247560
Revises: 
Create Date: 2021-11-06 19:13:36.438278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b5cc247560'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.String(length=320), nullable=False),
    sa.Column('Ingredient', sa.Text(), nullable=False),
    sa.Column('sales', sa.String(length=200), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('uploaded_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu')),
    sa.UniqueConstraint('name', name=op.f('uq_menu_name')),
    mysql_collate='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    # ### end Alembic commands ###
