"""empty message

Revision ID: 0c077a7632f9
Revises: ab503e8decaf
Create Date: 2021-11-06 19:35:17.637192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c077a7632f9'
down_revision = 'ab503e8decaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_constraint('uq_menu_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_menu_name', ['name'])

    # ### end Alembic commands ###
