"""empty message

Revision ID: 62d3e3fea7bf
Revises: f3649a69c537
Create Date: 2021-11-16 16:34:29.954548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d3e3fea7bf'
down_revision = 'f3649a69c537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales', sa.Integer(), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('sales')

    # ### end Alembic commands ###
