"""empty message

Revision ID: ab503e8decaf
Revises: 055391d9f45f
Create Date: 2021-11-06 19:33:47.509345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab503e8decaf'
down_revision = '055391d9f45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=False))
        batch_op.drop_column('ingredient')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient', sa.TEXT(), nullable=False))
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
