"""empty message

Revision ID: ba1001b2d76c
Revises: 5919bf3099c3
Create Date: 2021-11-07 00:38:35.696990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1001b2d76c'
down_revision = '5919bf3099c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_review_review_id_menu', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_review_menu_id_menu'), 'menu', ['menu_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('review_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_review_menu_id_menu'), type_='foreignkey')
        batch_op.create_foreign_key('fk_review_review_id_menu', 'menu', ['review_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('menu_id')

    # ### end Alembic commands ###
